# Generated by Django 3.1.2 on 2021-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='file/', verbose_name='添付ファイル'),
        ),
    ]
