# Generated by Django 3.1.2 on 2021-06-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_topic_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mime',
            field=models.TextField(blank=True, default='', verbose_name='MIMEタイプ'),
        ),
    ]
