# Generated by Django 3.1.2 on 2021-07-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_topic_mime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('attachment', models.FileField(blank=True, default='', upload_to='file/', verbose_name='添付ファイル')),
                ('mime', models.TextField(blank=True, default='', verbose_name='MIMEタイプ')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.topic', verbose_name='リプライ対象のトピック')),
            ],
            options={
                'db_table': 'topic_reply',
            },
        ),
    ]
